name: Build Packages
on:
  push:
    branches:
      - master
    #tags:
     # - 'v*.*.*.*'
    workflow_dispatch:
        inputs:
            make-rpm:
                description: "Make a RPM Package"
                required: " false"
                type: boolean
                default: true
jobs:
  main:
    runs-on: "ubuntu-latest" # self-hosted
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build RPM package
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
            spec_file: "main.spec"


      #- name: Package Binaries
        #run: build-packages ${{github.repository}} ${{github.workspace}} --env NPM_AUTH_TOKEN ${{secrets.NPM_AUTH_PAT}}
      - name: Set Variables
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "PRERELEASE=$(cat ${{github.workspace}}/manifest.json | jq --raw-output '.prerelease')" >> $GITHUB_ENV
          echo "TITLE=$(cat ${{github.workspace}}/manifest.json | jq --raw-output '.title')" >> $GITHUB_ENV
          echo "VERSION=$(cat ${{github.workspace}}/manifest.json | jq --raw-output '.version')" >> $GITHUB_ENV
          echo "REVISION=$(cat ${{github.workspace}}/manifest.json | jq --raw-output '.buildVersion')" >> $GITHUB_ENV
      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: ${{env.TITLE}} ${{env.VERSION}}
          prerelease: ${{env.PRERELEASE}}
          body_path: ${{github.workspace}}/CHANGELOG.md
          files: |
            #${{github.workspace}}/dist/packages/*/*.deb
            ${{github.workspace}}/dist/packages/*/*.rpm
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Update Repository
        if: startsWith(github.ref, 'refs/tags/')
        run: update-repositories ${{github.workspace}}
      - name: Publish Repository
        if: startsWith(github.ref, 'refs/tags/')
        run: publish-repo
